/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    colors: {
      white: "white",
      black: "black",
      primary: "#FEF116",
      secondary: "#6B6B6B",
      yellow: "#FEF445",
      grey: "#6B6B6BCC",
      medium_white: "#F8F8F8",
      dark_grey: "#303030",
      medium_grey: "#939393",
      lite_grey: "#C7C7C7",
      table_grey: "#FAFAFA",
      slate_grey:"#A0A0A0",
      ash: "#959595",
      dark_ash: "#737373",
      medium_ash: "#353535",
      zinc:"#292626",
      skyBlue: "#9BE9FF",
      dark_skyBlue: "#1B94B5",
      medium_blue: "#DEFFFF",
      lite_skyBlue: "#F5F7FB",
      purple: "#BF91FF",
      lavender: "#ECD6D6CC",
      dark_lavender: "#B17A7A",
      pink: "#F58DC3",
      lite_pink: "#FCEDD4CC",
      green: "#B1F094",
      dark_green: "#91A672",
      medium_green: "#ECF9E2",
      lite_green: "#E7F5D3CC",
      blue: "#687FA4",
      medium_blue: "#D9E6FACC",
      brown: "#AB8851",
      medium_brown: "#FFF3DC",
      red: "#FF7D66",
      medium_red: "#F08989",
      lime: "#B9B902",
      emerald: "#089B08",
      cyan: "#0C8DB0",
    },
  },
  plugins: [require('tailwind-scrollbar-hide')],
};
