export const useTableFieldData = (titleName) => {
  const getFieldData = (type) => {
    if (type === "HO") {
      return {
        fieldObj: {
          REC: null,
          CTR: null,
          DEPT: null,
          EMPLOYEEID: null,
          BADGE: null,
          NAME: null,
          DATE: null,
          ONAM: null,
          OFFAM: null,
          ONPM: null,
          OFFPM: null,
          IN: null,
          OUT: null,
          TOTALINOUT: null,
          ALLDAYMINUTES: null,
          NETMINUTES: null,
          TOTALHOURS: null,
          NORMALWORKINGHRSPERDAY: null,
          TOTALACTUALHOURS: null,
          OT: null,
          REMARKS: null,
        },
        fields: [
          "REC",
          "CTR",
          "DEPT",
          "EMPLOYEEID",
          "BADGE",
          "NAME",
          "DATE",
          "ONAM",
          "OFFAM",
          "ONPM",
          "OFFPM",
          "IN",
          "OUT",
          "TOTALINOUT",
          "ALLDAYMINUTES",
          "NETMINUTES",
          "TOTALHOURS",
          "NORMALWORKINGHRSPERDAY",
          "TOTALACTUALHOURS",
          "OT",
          "REMARKS",
        ],
        tableHeader: [
          "REC#",
          "CTR",
          "DEPT",
          "EMPLOYEE ID",
          "BADGE#",
          "NAME",
          "DATE",
          "ON AM",
          "OFF AM",
          "ON PM",
          "OFF PM",
          "IN",
          "OUT",
          "TOTAL IN/OUT",
          "ALL DAY MINUTES",
          "NET MINUTES",
          "TOTAL HOURS",
          "NORMAL WORKING HRS PER DAY",
          "TOTAL ACTUAL HOURS",
          "OT",
          "REMARKS",
        ],
      };
      // return { fieldObj, fields, tableHeader };
    }

    {
      /* {{
                  BPCOMPANY: "ADININ WORKS & ENGINEERING SDN BHD",
                  DAILY: "12h 47m",
                  DAILYTOTAL: "12h 47m",
                  DAYDIFFERENCE: 0,
                  EARLIESTENTRYTIME: ["02/12/2024 05:56:49 am"],
                  ENTRANCEDATE: "12/2/2024",
                  ENTRYTIME: ["02/12/2024 05:56:49 am"],
                  EXITTIME: ["02/12/2024 06:43:23 pm"],
                  FID: 596,
                  LATESTENTRYTIME: ["02/12/2024 06:43:23 pm"],
                  NAMEFLAST: "UNTING AK GENA",
                  NORMALWORKINGHRSPERDAY: "7",
                  OT: "",
                  REMARKS: "",
                  WORKINGHOURS: "",
                }} */
    }
    if (type === "BLNG") {
      return {
        fieldObj: {
          BPCOMPANY:null,
          FID: null,
          NAMEFLAST: null,
          ENTRANCEDATE: null,
          EARLIESTENTRYTIME:null,
          LATESTENTRYTIME:null,
          ENTRYTIME: null,
          EXITTIME: null,
          // DAYDIFFERENCE: null,
          DAILYTOTAL: null,

          DAILY: null,
          NORMALWORKINGHRSPERDAY: null,
          WORKINGHOURS: null,
          OT: null,
          REMARKS: null,
          // STATUS: null,
        },

        fields: [
          "BPCOMPANY",
          "FID",
          "NAMEFLAST",
          "ENTRANCEDATE",
          "EARLIESTENTRYTIME",
          "LATESTENTRYTIME",
          "ENTRYTIME",
          "EXITTIME",
          // "DAYDIFFERENCE",
          "DAILYTOTAL",
          "DAILY",
          "NORMALWORKINGHRSPERDAY",
          "WORKINGHOURS",
          "OT",
          "REMARKS",
        ],

        tableHeader: [
          "BPCOMPANY",
          "FID",
          "NAME (FLAST)",
          "ENTRANCE DATE",
          "EARLIEST ENTRYTIME",
          "LATEST ENTRYTIME",
          "ENTRY TIME",
          "EXIT TIME",
          // "DAY DIFFERENCE",
          "DAILY TOTAL",
          "DAILY",
          "NORMAL WORKING HRS PER DAY",
          "ACTUAL WORKING HOURS",
          "OT",
          // "JOB CODE",
          // "LOCATION",
          "REMARKS",
        ],
      };
    }
    if (type === "SBW") {
      return {
        fieldObj: {
          NAME: null,
          DEPTDIV: null,
          BADGE: null,
          DATE: null,
          IN: null,
          OUT: null,
          TOTALINOUT: null,
          ALLDAYMINHRS: null,
          NETMINUTES: null,
          TOTALHOURS: null,
          NORMALWORKINGHRSPERDAY: null,
          WORKINGHOURS: null,
          OT: null,
          REMARKS: null,
        },
        fields: [
          "NAME",
          "DEPTDIV",
          "BADGE",
          "DATE",
          "IN",
          "OUT",
          "TOTALINOUT",
          "ALLDAYMINHRS",
          "NETMINUTES",
          "TOTALHOURS",
          "NORMALWORKINGHRSPERDAY",
          "WORKINGHOURS",
          "OT",
          "REMARKS",
        ],
        tableHeader: [
          "NAME",
          "DEPT/DIV",
          "BADGE#",
          "DATE",
          "IN",
          "OUT",
          "TOTAL IN/OUT",
          "ALL DAY MIN (HRS)",
          "NET MINUTES",
          "TOTAL HOURS",
          "NORMAL WORKING HRS PER DAY",
          "ACTUAL WORKING HOURS",
          "OT",
          "REMARKS",
        ],
      };
    }
    if (type === "ORMC") {
      return {
        fieldObj: {
          NAME: null,
          DEPTDIV: null,
          BADGE: null,
          DATE: null,
          IN: null,
          OUT: null,
          TOTALINOUT: null,
          ALLDAYMINHRS: null,
          NETMINUTES: null,
          TOTALHOURS: null,
          NORMALWORKINGHRSPERDAY: null,
          WORKINGHOURS: null,
          OT: null,
          REMARKS: null,
        },
        fields: [
          "NAME",
          "DEPTDIV",
          "BADGE",
          "DATE",
          "IN",
          "OUT",
          "TOTALINOUT",
          "ALLDAYMINHRS",
          "NETMINUTES",
          "TOTALHOURS",
          "NORMALWORKINGHRSPERDAY",
          "WORKINGHOURS",
          "OT",
          "REMARKS",
        ],
        tableHeader: [
          "Name",
          "DEPT/DIV",
          "BADGE#",
          "DATE",
          "IN",
          "OUT",
          "TOTAL IN/OUT",
          "ALL DAY MIN (HRS)",
          "NET MINUTES",
          "TOTAL HOURS",
          "NORMAL WORKING HRS PER DAY",
          "ACTUAL WORKING HOURS",
          "OT",
          "REMARKS",
        ],
      };
    }
    if (type === "Offshore") {
      return {
        fieldObj: {
          NAME: null,
          TRADE: null,
          NO: null,
          LOCATION: null,
          DATE: null,
          TOTALHOURS: null,
          TOTALHOURS2: null,
          TOTALHOURS3: null,
          NORMALWORKINGHRSPERDAY: null,
          WORKINGHOURS: null,
          OT: null,
          REMARKS: null,
        },
        fields: [
          "NAME",
          "TRADE",
          "NO",
          "LOCATION",
          "DATE",
          "TOTALHOURS",
          "TOTALHOURS2",
          "TOTALHOURS3",
          "NORMALWORKINGHRSPERDAY",
          "WORKINGHOURS",
          "OT",
          "REMARKS",
        ],
        tableHeader: [
          "EMPLOYEE NAME",
          "TRADE",
          "SAP ID",
          "LOCATION",
          "DATE",
          "TOTAL NT",
          "TOTAL OT",
          "TOTAL IN/OUT",
          "NORMAL WORKING HRS PER DAY",
          "ACTUAL WORKING HOURS",
          "OT",
          "REMARKS",
        ],
      };
    }
  };
  const AllFieldData = getFieldData(titleName);
  return AllFieldData;
};
