export const RecruitmentPaths = [
  "/recruitment",
  "/recrutiles",
  "/recrutiles/candidate",
  "/recrutiles/applyemployreq",
  "/recrutiles/listofcandi",
  "/recrutiles/localcandi",
  "/recrutiles/nonloccandi",
  "/recrutiles/employreq",
  "/recrutiles/status",
  "/recrutiles/workpasstracking",
  "/addCandidates",
  "/addCandidates/personalDetails",
  "/addCandidates/educationDetails",
  "/addCandidates/otherDetails",
  "/hiringJob",
  "/postJob",
];
export const EmployeePaths = [
  "/employee",
  "/allempDetails",
  "/employeeInfo",
  "/insuranceAdd",
  "/workInfo",
  "/labourImmigration",
  "/workPass",
  "/nonLocalAcco",
  "/insuranceAdd/employeeInsurances",
  "/insuranceAdd/dependentInsurance",
  "/sawp",
  "/sawp/doe",
  "/sawp/nlms",
  "/sawp/bankGuarantee",
  "/sawp/jitpa",
  "/sawp/labourDeposit",
  "/sawp/immigration",
  "/empRequistion",
  "/employeeInfo",
  "/workInfo",
  "/workPass",
  "/nonLocalAcco",
  "/labourImmigration",
];
export const InsurancePaths = [
  "/insuranceHr",
  "/insuranceHr/groupHS",
  "/insuranceHr/workmenComp",
  "/insuranceHr/travelling",
  "/insuranceHr/personalAcci",
  "/insuranceHr/insuranceClaim",
];
export const LeaveManagement = [
  "/leaveManagement",
  "/leaveManagement/historyLeave",
  "/leaveManagement/leaveBalance",
  "/leaveManagement/requestTickets",
];

export const TimePaths = [
  "/timeSheet",
  "/timesheetHO",
  "/timesheetSBW",
  "/timesheetORMC",
  "/timesheetOffshore",
  "/timesheetBlng",
  "/viewTimesheet",
  "/viewSummary",
];
export const TrainingPaths = [
  "/training",
  "/training/hr",
  "/training/AcTc",
  "/training/trainingCertify",
  "/trainingReq",
  "/trainingReq/add",
  "/trainingReq/view",
  "/blngCertify",
  "/omgCertify",
  "/training/tcView",
];

export const UserPaths = ["/user", "/addNewForm"];
export const ReportPaths = [
  "/reports",
  "/probForm",
  "/contractForms",
  "/rm",
  "/filterTable",
  "/resignation",
  "/termination",
  "/probationReview",
  "/contractReview",
  "/empPassExpiry",
  "/ldExpiry",
  "/passportExpiry",
  "/empMedical",
  "/newRecruit",
  "/trainingRC",
  "/lbdKpi",
  "/groupHS",
  "/leavePass",
  "/contractForms",
  "/promotion",
  "/probFormUpdate",
  "/ContractUp"
];
