export const LMDetails = [
  {
    empID: "AWE201",
    name: "Tony",
    badge: "5058",
    deptDev: "5067",
    jobTitle: "Trainer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/01/2024",
    "superior Name": "John Doe",
    "approved Date": "08/02/2024",
    "manager Name": "Jane Smith",
    "manager Approved Date": "08/03/2024",
    "leave Type": "Sick Leave",
    "start Date": "08/19/2024",
    "end Date": "08/20/2024",
    "no of days": "2 Days",
    "no of leave remaining": "12 Days",
    reason: "Personal Issues",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE202",
    name: "Sara",
    badge: "5059",
    deptDev: "5067",
    jobTitle: "Developer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/04/2024",
    "superior Name": "Michael Brown",
    "approved Date": "08/05/2024",
    "manager Name": "Emily White",
    "manager Approved Date": "08/06/2024",
    "leave Type": "Annual Leave",
    "start Date": "08/10/2024",
    "end Date": "08/15/2024",
    "no of days": "5 Days",
    "no of leave remaining": "67 Days",
    reason: "Vacation",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE203",
    name: "John",
    badge: "5060",
    deptDev: "5067",
    jobTitle: "Designer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/07/2024",
    "superior Name": "Alice Johnson",
    "approved Date": "08/08/2024",
    "manager Name": "Chris Lee",
    "manager Approved Date": "08/09/2024",
    "leave Type": "Sick Leave",
    "start Date": "08/11/2024",
    "end Date": "08/12/2024",
    "no of days": "2 Days",
    "no of leave remaining": "22 Days",
    reason: "Flu",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE204",
    name: "Mike",
    badge: "5061",
    deptDev: "5067",
    jobTitle: "Tester",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/10/2024",
    "superior Name": "Anna Taylor",
    "approved Date": "08/11/2024",
    "manager Name": "David Green",
    "manager Approved Date": "08/12/2024",
    "leave Type": "Emergency Leave",
    "start Date": "08/18/2024",
    "end Date": "08/19/2024",
    "no of days": "1 Day",
    "no of leave remaining": "42 Days",
    reason: "Family Emergency",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE205",
    name: "Nina",
    badge: "5062",
    deptDev: "5067",
    jobTitle: "Project Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/13/2024",
    "superior Name": "Robert King",
    "approved Date": "08/14/2024",
    "manager Name": "Laura Adams",
    "manager Approved Date": "08/15/2024",
    "leave Type": "Maternity Leave",
    "start Date": "08/20/2024",
    "end Date": "09/20/2024",
    "no of days": "30 Days",
    "no of leave remaining": "23 Days",
    reason: "Maternity",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE206",
    name: "Sam",
    badge: "5063",
    deptDev: "5067",
    jobTitle: "HR Specialist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/16/2024",
    "superior Name": "Paul Wright",
    "approved Date": "08/17/2024",
    "manager Name": "Sara Mitchell",
    "manager Approved Date": "08/18/2024",
    "leave Type": "Sick Leave",
    "start Date": "08/22/2024",
    "end Date": "08/23/2024",
    "no of days": "2 Days",
    "no of leave remaining": "120 Days",
    reason: "Health Issues",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE207",
    name: "Tina",
    badge: "5064",
    deptDev: "5067",
    jobTitle: "Sales Associate",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/19/2024",
    "superior Name": "Chris Nolan",
    "approved Date": "08/20/2024",
    "manager Name": "Tim Brown",
    "manager Approved Date": "08/21/2024",
    "leave Type": "Annual Leave",
    "start Date": "09/01/2024",
    "end Date": "09/05/2024",
    "no of days": "5 Days",
    "no of leave remaining": "132 Days",
    reason: "Family Trip",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE208",
    name: "Liam",
    badge: "5065",
    deptDev: "5067",
    jobTitle: "Marketing Specialist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/22/2024",
    "superior Name": "Julia Roberts",
    "approved Date": "08/23/2024",
    "manager Name": "Emma Watson",
    "manager Approved Date": "08/24/2024",
    "leave Type": "Compassionate Leave",
    "start Date": "09/07/2024",
    "end Date": "09/08/2024",
    "no of days": "2 Days",
    "no of leave remaining": "130 Days",
    reason: "Sick Family Member",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE209",
    name: "Sophia",
    badge: "5066",
    deptDev: "5067",
    jobTitle: "Data Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/25/2024",
    "superior Name": "Lucas Scott",
    "approved Date": "08/26/2024",
    "manager Name": "Olivia Brown",
    "manager Approved Date": "08/27/2024",
    "leave Type": "Sick Leave",
    "start Date": "09/10/2024",
    "end Date": "09/11/2024",
    "no of days": "2 Days",
    "no of leave remaining": "149 Days",
    reason: "Medical Checkup",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE210",
    name: "Mia",
    badge: "5067",
    deptDev: "5067",
    jobTitle: "Accountant",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "08/29/2024",
    "superior Name": "Charles Davis",
    "approved Date": "08/30/2024",
    "manager Name": "Isabella Clark",
    "manager Approved Date": "08/31/2024",
    "leave Type": "Personal Leave",
    "start Date": "09/12/2024",
    "end Date": "09/13/2024",
    "no of days": "2 Days",
    "no of leave remaining": "42 Days",
    reason: "Personal Reasons",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE211",
    name: "Oliver",
    badge: "5068",
    deptDev: "5067",
    jobTitle: "Software Engineer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/01/2024",
    "superior Name": "Zoe Harris",
    "approved Date": "09/02/2024",
    "manager Name": "Jack Martin",
    "manager Approved Date": "09/03/2024",
    "leave Type": "Annual Leave",
    "start Date": "09/15/2024",
    "end Date": "09/20/2024",
    "no of days": "5 Days",
    "no of leave remaining": "22 Days",
    reason: "Travel Plans",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE212",
    name: "Ella",
    badge: "5069",
    deptDev: "5067",
    jobTitle: "HR Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/05/2024",
    "superior Name": "Kevin Thompson",
    "approved Date": "09/06/2024",
    "manager Name": "Nancy Perez",
    "manager Approved Date": "09/07/2024",
    "leave Type": "Sick Leave",
    "start Date": "09/21/2024",
    "end Date": "09/22/2024",
    "no of days": "2 Days",
    "no of leave remaining": "32 Days",
    reason: "Flu Symptoms",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE213",
    name: "James",
    badge: "5070",
    deptDev: "5067",
    jobTitle: "Content Writer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/08/2024",
    "superior Name": "Rachel Adams",
    "approved Date": "09/09/2024",
    "manager Name": "Laura James",
    "manager Approved Date": "09/10/2024",
    "leave Type": "Annual Leave",
    "start Date": "09/25/2024",
    "end Date": "09/30/2024",
    "no of days": "5 Days",
    "no of leave remaining": "77 Days",
    reason: "Holiday Trip",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE214",
    name: "Ava",
    badge: "5071",
    deptDev: "5067",
    jobTitle: "Operations Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/12/2024",
    "superior Name": "Brian Wilson",
    "approved Date": "09/13/2024",
    "manager Name": "Kathy Brown",
    "manager Approved Date": "09/14/2024",
    "leave Type": "Compassionate Leave",
    "start Date": "10/01/2024",
    "end Date": "10/02/2024",
    "no of days": "2 Days",
    "no of leave remaining": "62 Days",
    reason: "Family Issue",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE215",
    name: "Liam",
    badge: "5072",
    deptDev: "5067",
    jobTitle: "Graphic Designer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/15/2024",
    "superior Name": "Alex Turner",
    "approved Date": "09/16/2024",
    "manager Name": "Sophia Moore",
    "manager Approved Date": "09/17/2024",
    "leave Type": "Sick Leave",
    "start Date": "10/05/2024",
    "end Date": "10/06/2024",
    "no of days": "2 Days",
    "no of leave remaining": "56 Days",
    reason: "Severe Headache",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE216",
    name: "Ethan",
    badge: "5073",
    deptDev: "5067",
    jobTitle: "Business Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/18/2024",
    "superior Name": "Megan Fox",
    "approved Date": "09/19/2024",
    "manager Name": "William Harris",
    "manager Approved Date": "09/20/2024",
    "leave Type": "Annual Leave",
    "start Date": "10/10/2024",
    "end Date": "10/15/2024",
    "no of days": "5 Days",
    "no of leave remaining": "34 Days",
    reason: "Family Vacation",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE217",
    name: "Isabella",
    badge: "5074",
    deptDev: "5067",
    jobTitle: "UX Researcher",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/22/2024",
    "superior Name": "Jake White",
    "approved Date": "09/23/2024",
    "manager Name": "Emily Davis",
    "manager Approved Date": "09/24/2024",
    "leave Type": "Personal Leave",
    "start Date": "10/20/2024",
    "end Date": "10/21/2024",
    "no of days": "2 Days",
    "no of leave remaining": "77 Days",
    reason: "Personal Matters",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE218",
    name: "Mason",
    badge: "5075",
    deptDev: "5067",
    jobTitle: "IT Support",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/25/2024",
    "superior Name": "Lucas Gray",
    "approved Date": "09/26/2024",
    "manager Name": "Sarah Carter",
    "manager Approved Date": "09/27/2024",
    "leave Type": "Sick Leave",
    "start Date": "10/22/2024",
    "end Date": "10/23/2024",
    "no of days": "2 Days",
    "no of leave remaining": "11 Days",
    reason: "Back Pain",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE219",
    name: "Charlotte",
    badge: "5076",
    deptDev: "5067",
    jobTitle: "Database Administrator",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "09/29/2024",
    "superior Name": "Robert King",
    "approved Date": "09/30/2024",
    "manager Name": "Alice Johnson",
    "manager Approved Date": "10/01/2024",
    "leave Type": "Emergency Leave",
    "start Date": "11/01/2024",
    "end Date": "11/01/2024",
    "no of days": "1 Day",
    "no of leave remaining": "82 Days",
    reason: "Urgent Family Matter",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE220",
    name: "Aiden",
    badge: "5077",
    deptDev: "5067",
    jobTitle: "Network Engineer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/02/2024",
    "superior Name": "Evelyn Brown",
    "approved Date": "10/03/2024",
    "manager Name": "David Smith",
    "manager Approved Date": "10/04/2024",
    "leave Type": "Sick Leave",
    "start Date": "11/05/2024",
    "end Date": "11/06/2024",
    "no of days": "2 Days",
    "no of leave remaining": "33 Days",
    reason: "High Fever",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE221",
    name: "Ella",
    badge: "5078",
    deptDev: "5067",
    jobTitle: "Product Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/07/2024",
    "superior Name": "Johnathan Smith",
    "approved Date": "10/08/2024",
    "manager Name": "Rachel Green",
    "manager Approved Date": "10/09/2024",
    "leave Type": "Annual Leave",
    "start Date": "11/10/2024",
    "end Date": "11/15/2024",
    "no of days": "5 Days",
    "no of leave remaining": "55 Days",
    reason: "Traveling Abroad",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE222",
    name: "Elijah",
    badge: "5079",
    deptDev: "5067",
    jobTitle: "Software Architect",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/12/2024",
    "superior Name": "Hannah Taylor",
    "approved Date": "10/13/2024",
    "manager Name": "Brian Johnson",
    "manager Approved Date": "10/14/2024",
    "leave Type": "Compassionate Leave",
    "start Date": "11/20/2024",
    "end Date": "11/21/2024",
    "no of days": "2 Days",
    "no of leave remaining": "88 Days",
    reason: "Family Health Issues",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE223",
    name: "Zoe",
    badge: "5080",
    deptDev: "5067",
    jobTitle: "Security Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/15/2024",
    "superior Name": "Adam Scott",
    "approved Date": "10/16/2024",
    "manager Name": "Nora White",
    "manager Approved Date": "10/17/2024",
    "leave Type": "Sick Leave",
    "start Date": "12/01/2024",
    "end Date": "12/02/2024",
    "no of days": "2 Days",
    "no of leave remaining": "45 Days",
    reason: "Migraine",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE224",
    name: "Lucas",
    badge: "5081",
    deptDev: "5067",
    jobTitle: "DevOps Engineer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/18/2024",
    "superior Name": "Oliver Harris",
    "approved Date": "10/19/2024",
    "manager Name": "Sophia Clark",
    "manager Approved Date": "10/20/2024",
    "leave Type": "Annual Leave",
    "start Date": "12/10/2024",
    "end Date": "12/15/2024",
    "no of days": "5 Days",
    "no of leave remaining": "11 Days",
    reason: "Holiday with Family",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE225",
    name: "Mason",
    badge: "5082",
    deptDev: "5067",
    jobTitle: "Cloud Engineer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/21/2024",
    "superior Name": "Ella James",
    "approved Date": "10/22/2024",
    "manager Name": "Noah Brown",
    "manager Approved Date": "10/23/2024",
    "leave Type": "Personal Leave",
    "start Date": "12/25/2024",
    "end Date": "12/26/2024",
    "no of days": "2 Days",
    "no of leave remaining": "43 Days",
    reason: "Family Gathering",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE226",
    name: "Grace",
    badge: "5083",
    deptDev: "5067",
    jobTitle: "Marketing Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/24/2024",
    "superior Name": "James White",
    "approved Date": "10/25/2024",
    "manager Name": "Mia Green",
    "manager Approved Date": "10/26/2024",
    "leave Type": "Sick Leave",
    "start Date": "01/01/2025",
    "end Date": "01/02/2025",
    "no of days": "2 Days",
    "no of leave remaining": "22 Days",
    reason: "High Fever",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE227",
    name: "Henry",
    badge: "5084",
    deptDev: "5067",
    jobTitle: "Content Strategist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "10/28/2024",
    "superior Name": "Sarah Williams",
    "approved Date": "10/29/2024",
    "manager Name": "Jacob Johnson",
    "manager Approved Date": "10/30/2024",
    "leave Type": "Annual Leave",
    "start Date": "01/05/2025",
    "end Date": "01/10/2025",
    "no of days": "5 Days",
    "no of leave remaining": "33 Days",
    reason: "Family Vacation",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE228",
    name: "Ava",
    badge: "5085",
    deptDev: "5067",
    jobTitle: "Product Owner",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/01/2024",
    "superior Name": "Daniel Brown",
    "approved Date": "11/02/2024",
    "manager Name": "Sophia Lee",
    "manager Approved Date": "11/03/2024",
    "leave Type": "Compassionate Leave",
    "start Date": "01/15/2025",
    "end Date": "01/16/2025",
    "no of days": "2 Days",
    "no of leave remaining": "99 Days",
    reason: "Illness in Family",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE229",
    name: "Elena",
    badge: "5086",
    deptDev: "5067",
    jobTitle: "Customer Service Rep",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/05/2024",
    "superior Name": "Timothy Clark",
    "approved Date": "11/06/2024",
    "manager Name": "Olivia Martinez",
    "manager Approved Date": "11/07/2024",
    "leave Type": "Sick Leave",
    "start Date": "01/20/2025",
    "end Date": "01/21/2025",
    "no of days": "2 Days",
    "no of leave remaining": "32 Days",
    reason: "Migraine",
    status: "Pending",
    "submitted Form": "View",
  },
  {
    empID: "AWE230",
    name: "Liam",
    badge: "5087",
    deptDev: "5067",
    jobTitle: "Sales Executive",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/10/2024",
    "superior Name": "Emma Wilson",
    "approved Date": "11/11/2024",
    "manager Name": "Noah Thomas",
    "manager Approved Date": "11/12/2024",
    "leave Type": "Annual Leave",
    "start Date": "02/01/2025",
    "end Date": "02/05/2025",
    "no of days": "5 Days",
    "no of leave remaining": "12 Days",
    reason: "Winter Trip",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE231",
    name: "Aiden",
    badge: "5088",
    deptDev: "5067",
    jobTitle: "Network Administrator",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/15/2024",
    "superior Name": "Ava Roberts",
    "approved Date": "11/16/2024",
    "manager Name": "James Brown",
    "manager Approved Date": "11/17/2024",
    "leave Type": "Sick Leave",
    "start Date": "02/10/2025",
    "end Date": "02/11/2025",
    "no of days": "2 Days",
    "no of leave remaining": "42 Days",
    reason: "Flu Symptoms",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE232",
    name: "Sofia",
    badge: "5089",
    deptDev: "5067",
    jobTitle: "Technical Writer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/20/2024",
    "superior Name": "Lucas Thompson",
    "approved Date": "11/21/2024",
    "manager Name": "Ella White",
    "manager Approved Date": "11/22/2024",
    "leave Type": "Personal Leave",
    "start Date": "02/15/2025",
    "end Date": "02/16/2025",
    "no of days": "2 Days",
    "no of leave remaining": "5 Days",
    reason: "Personal Matters",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE233",
    name: "William",
    badge: "5090",
    deptDev: "5067",
    jobTitle: "Research Scientist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/25/2024",
    "superior Name": "Olivia Harris",
    "approved Date": "11/26/2024",
    "manager Name": "David Moore",
    "manager Approved Date": "11/27/2024",
    "leave Type": "Emergency Leave",
    "start Date": "02/20/2025",
    "end Date": "02/21/2025",
    "no of days": "2 Days",
    "no of leave remaining": "3 Days",
    reason: "Urgent Family Matter",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE234",
    name: "Mia",
    badge: "5091",
    deptDev: "5067",
    jobTitle: "Quality Assurance",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "11/30/2024",
    "superior Name": "Aiden Clark",
    "approved Date": "12/01/2024",
    "manager Name": "Emma King",
    "manager Approved Date": "12/02/2024",
    "leave Type": "Sick Leave",
    "start Date": "03/01/2025",
    "end Date": "03/02/2025",
    "no of days": "2 Days",
    "no of leave remaining": "3 Days",
    reason: "Stomach Issues",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE235",
    name: "Noah",
    badge: "5092",
    deptDev: "5067",
    jobTitle: "Web Developer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/05/2024",
    "superior Name": "Sophia Johnson",
    "approved Date": "12/06/2024",
    "manager Name": "Liam Garcia",
    "manager Approved Date": "12/07/2024",
    "leave Type": "Annual Leave",
    "start Date": "03/10/2025",
    "end Date": "03/15/2025",
    "no of days": "5 Days",
    "no of leave remaining": "52 Days",
    reason: "Spring Break",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE236",
    name: "Chloe",
    badge: "5093",
    deptDev: "5067",
    jobTitle: "Sales Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/10/2024",
    "superior Name": "Michael Lee",
    "approved Date": "12/11/2024",
    "manager Name": "Emma Roberts",
    "manager Approved Date": "12/12/2024",
    "leave Type": "Sick Leave",
    "start Date": "03/20/2025",
    "end Date": "03/21/2025",
    "no of days": "2 Days",
    "no of leave remaining": "66 Days",
    reason: "Chest Pain",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE237",
    name: "Oliver",
    badge: "5094",
    deptDev: "5067",
    jobTitle: "SEO Specialist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/15/2024",
    "superior Name": "Ava Thompson",
    "approved Date": "12/16/2024",
    "manager Name": "James Brown",
    "manager Approved Date": "12/17/2024",
    "leave Type": "Annual Leave",
    "start Date": "04/01/2025",
    "end Date": "04/05/2025",
    "no of days": "5 Days",
    "no of leave remaining": "2 Days",
    reason: "Vacation",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE238",
    name: "Lily",
    badge: "5095",
    deptDev: "5067",
    jobTitle: "Financial Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/20/2024",
    "superior Name": "Emily Walker",
    "approved Date": "12/21/2024",
    "manager Name": "David Carter",
    "manager Approved Date": "12/22/2024",
    "leave Type": "Compassionate Leave",
    "start Date": "04/10/2025",
    "end Date": "04/11/2025",
    "no of days": "2 Days",
    "no of leave remaining": "7 Days",
    reason: "Family Emergency",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE239",
    name: "Jacob",
    badge: "5096",
    deptDev: "5067",
    jobTitle: "HR Coordinator",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/25/2024",
    "superior Name": "Natalie Adams",
    "approved Date": "12/26/2024",
    "manager Name": "John Smith",
    "manager Approved Date": "12/27/2024",
    "leave Type": "Sick Leave",
    "start Date": "04/15/2025",
    "end Date": "04/16/2025",
    "no of days": "2 Days",
    "no of leave remaining": "26 Days",
    reason: "Severe Cold",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE240",
    name: "Grace",
    badge: "5097",
    deptDev: "5067",
    jobTitle: "Digital Marketing Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "12/30/2024",
    "superior Name": "Daniel Johnson",
    "approved Date": "12/31/2024",
    "manager Name": "Sophia Lee",
    "manager Approved Date": "01/01/2025",
    "leave Type": "Annual Leave",
    "start Date": "05/01/2025",
    "end Date": "05/05/2025",
    "no of days": "5 Days",
    "no of leave remaining": "28 Days",
    reason: "Family Reunion",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE241",
    name: "Ella",
    badge: "5098",
    deptDev: "5067",
    jobTitle: "Operations Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "01/05/2025",
    "superior Name": "Michael White",
    "approved Date": "01/06/2025",
    "manager Name": "Olivia Martin",
    "manager Approved Date": "01/07/2025",
    "leave Type": "Sick Leave",
    "start Date": "05/10/2025",
    "end Date": "05/11/2025",
    "no of days": "2 Days",
    "no of leave remaining": "26 Days",
    reason: "Back Pain",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE242",
    name: "Liam",
    badge: "5099",
    deptDev: "5067",
    jobTitle: "IT Specialist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "01/10/2025",
    "superior Name": "Chloe Green",
    "approved Date": "01/11/2025",
    "manager Name": "Noah Turner",
    "manager Approved Date": "01/12/2025",
    "leave Type": "Annual Leave",
    "start Date": "05/20/2025",
    "end Date": "05/25/2025",
    "no of days": "5 Days",
    "no of leave remaining": "28 Days",
    reason: "Summer Trip",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE243",
    name: "Sophia",
    badge: "5100",
    deptDev: "5067",
    jobTitle: "Customer Success Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "01/15/2025",
    "superior Name": "Ethan King",
    "approved Date": "01/16/2025",
    "manager Name": "Emma Davis",
    "manager Approved Date": "01/17/2025",
    "leave Type": "Compassionate Leave",
    "start Date": "06/01/2025",
    "end Date": "06/02/2025",
    "no of days": "2 Days",
    "no of leave remaining": "26 Days",
    reason: "Family Health Issues",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE244",
    name: "Mason",
    badge: "5101",
    deptDev: "5067",
    jobTitle: "Business Development Manager",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "01/20/2025",
    "superior Name": "Lucas Garcia",
    "approved Date": "01/21/2025",
    "manager Name": "Sophia Young",
    "manager Approved Date": "01/22/2025",
    "leave Type": "Sick Leave",
    "start Date": "06/10/2025",
    "end Date": "06/11/2025",
    "no of days": "2 Days",
    "no of leave remaining": "28 Days",
    reason: "High Blood Pressure",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE245",
    name: "Avery",
    badge: "5102",
    deptDev: "5067",
    jobTitle: "Software Tester",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "01/25/2025",
    "superior Name": "Oliver Smith",
    "approved Date": "01/26/2025",
    "manager Name": "Liam Johnson",
    "manager Approved Date": "01/27/2025",
    "leave Type": "Annual Leave",
    "start Date": "06/15/2025",
    "end Date": "06/20/2025",
    "no of days": "5 Days",
    "no of leave remaining": "26 Days",
    reason: "Beach Vacation",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE246",
    name: "Benjamin",
    badge: "5103",
    deptDev: "5067",
    jobTitle: "Project Coordinator",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "02/01/2025",
    "superior Name": "Emily White",
    "approved Date": "02/02/2025",
    "manager Name": "Jacob Harris",
    "manager Approved Date": "02/03/2025",
    "leave Type": "Sick Leave",
    "start Date": "07/01/2025",
    "end Date": "07/02/2025",
    "no of days": "2 Days",
    "no of leave remaining": "28 Days",
    reason: "Flu Symptoms",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE247",
    name: "Evelyn",
    badge: "5104",
    deptDev: "5067",
    jobTitle: "Content Editor",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "02/05/2025",
    "superior Name": "William Davis",
    "approved Date": "02/06/2025",
    "manager Name": "Olivia Brown",
    "manager Approved Date": "02/07/2025",
    "leave Type": "Personal Leave",
    "start Date": "07/10/2025",
    "end Date": "07/11/2025",
    "no of days": "2 Days",
    "no of leave remaining": "28 Days",
    reason: "Family Commitment",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE248",
    name: "Luna",
    badge: "5105",
    deptDev: "5067",
    jobTitle: "UX/UI Designer",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "02/10/2025",
    "superior Name": "Chloe Clark",
    "approved Date": "02/11/2025",
    "manager Name": "Noah Smith",
    "manager Approved Date": "02/12/2025",
    "leave Type": "Annual Leave",
    "start Date": "07/15/2025",
    "end Date": "07/20/2025",
    "no of days": "5 Days",
    "no of leave remaining": "26 Days",
    reason: "Traveling Abroad",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE249",
    name: "Jack",
    badge: "5106",
    deptDev: "5067",
    jobTitle: "Data Analyst",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "02/15/2025",
    "superior Name": "Sofia Johnson",
    "approved Date": "02/16/2025",
    "manager Name": "James White",
    "manager Approved Date": "02/17/2025",
    "leave Type": "Sick Leave",
    "start Date": "08/01/2025",
    "end Date": "08/02/2025",
    "no of days": "2 Days",
    "no of leave remaining": "22 Days",
    reason: "Migraine",
    status: "Approved",
    "submitted Form": "View",
  },
  {
    empID: "AWE250",
    name: "Isabella",
    badge: "5107",
    deptDev: "5067",
    jobTitle: "HR Specialist",
    selectDate: new Date().toISOString().split('T')[0],
    "received Date": "02/20/2025",
    "superior Name": "Mason King",
    "approved Date": "02/21/2025",
    "manager Name": "Ella Davis",
    "manager Approved Date": "02/22/2025",
    "leave Type": "Emergency Leave",
    "start Date": "08/05/2025",
    "end Date": "08/06/2025",
    "no of days": "2 Days",
    "no of leave remaining": "22 Days",
    reason: "House Emergency",
    status: "Approved",
    "submitted Form": "View",
  },
];




